"""Add created_by field to products

Revision ID: b14fdb2a0fff
Revises: bc3cbe86d8ef
Create Date: 2025-06-16 14:52:10.491482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14fdb2a0fff'
down_revision: Union[str, None] = 'bc3cbe86d8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'created_by')
    # ### end Alembic commands ###
